name: einkaufsliste
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.13.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "images/home.png"


flutter:


  uses-material-design: true
  assets:
    - images/shopping.png
    - images/Aldi.png
    - images/Netto.png
    - images/Penny.png
    - images/home.png
    - images/splash.png

  